version: '3.5'
services:

    # Apache Hadoop

    hdfs-namenode-01:
        image: adruzenko/kbd-hadoop3:3.2.0
        hostname: hdfs-namenode-01
        command: hadoop namenode
        environment:
            - DFS_NAMENODE_NAME_DIR=/var/local/hadoop/dfs/namenode
        ports:
            - "9870:9870"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "${KBD_DATA_DIR}/hdfs-namenode-01/logs:/var/log/hadoop"
            - "${KBD_DATA_DIR}/hdfs-namenode-01/dfs:/var/local/hadoop/dfs"
        networks:
            playground-net:

    hdfs-datanode-01:
        image: adruzenko/kbd-hadoop3:3.2.0
        hostname: hdfs-datanode-01
        command: hadoop datanode
        ports:
            - "9864:9864"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "${KBD_DATA_DIR}/hdfs-datanode-01/logs:/var/log/hadoop"
            - "${KBD_DATA_DIR}/hdfs-datanode-01/dfs:/var/local/hadoop/dfs"
        networks:
            playground-net:
        depends_on:
            - hdfs-namenode-01

    yarn-resourcemanager-01:
        image: adruzenko/kbd-hadoop3:3.2.0
        hostname: yarn-resourcemanager-01
        command: hadoop resourcemanager
        ports:
            - "8088:8088"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "${KBD_DATA_DIR}/yarn-resourcemanager-01/logs:/var/log/hadoop"
        networks:
            playground-net:

    yarn-nodemanager-01:
        image: adruzenko/kbd-hadoop3:3.2.0
        hostname: yarn-nodemanager-01
        command: hadoop nodemanager
        ports:
            - "8042:8042"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "${KBD_DATA_DIR}/yarn-nodemanager-01/logs:/var/log/hadoop"
            - "${KBD_DATA_DIR}/yarn-nodemanager-01/tmp/mapred:/tmp/mapred"
        networks:
            playground-net:
        depends_on:
            - yarn-resourcemanager-01

    mapred-historyserver-01:
        image: adruzenko/kbd-hadoop3:3.2.0
        hostname: mapred-historyserver-01
        command: hadoop historyserver
        ports:
            - "19888:19888"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "${KBD_DATA_DIR}/mapred-historyserver-01/logs:/var/log/hadoop"
            - "${KBD_DATA_DIR}mapred-historyserver-01/tmp/mapred:/tmp/mapred"
        networks:
            playground-net:
        depends_on:
            - yarn-resourcemanager-01

    hdfs-edge-hadoop:
        image: adruzenko/kbd-hadoop3:3.2.0
        user: hadoop
        hostname: hdfs-edge-hadoop
        command: tail -f /dev/null
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "./../../data/hadoop_session_01/word_count:/bdpc/data/word_count/input"
            - "./../../data/hadoop_session_01/word_count_gzip:/bdpc/data/word_count_gzip/input"
            - "./../../apps/mapreduce:/bdpc/apps/mapreduce"
            - "./../../apps/scripts:/bdpc/scripts"
        networks:
            playground-net:
        depends_on:
            - hdfs-namenode-01
            - hdfs-datanode-01
            - yarn-resourcemanager-01
            - yarn-nodemanager-01
            - mapred-historyserver-01

networks:
  playground-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.102.0.0/24
