version: '3.5'
services:

    # Apache Zookeeper
    zoo-node-01:
        image: zookeeper:3.5.5
        hostname: zoo-node-01
        restart: always
        volumes:
            - "${KBD_DATA_DIR}/zoo-node-01/data:/data"
            - "${KBD_DATA_DIR}/zoo-node-01/datalog:/datalog"
            - "${KBD_DATA_DIR}/zoo-node-01/logs:/logs"
        environment:
            ZOO_MY_ID: 1
        networks:
            playground-net:

    # Apache Hadoop

    hdfs-namenode-01:
        image: adruzenko/kbd-hadoop3:3.2.0
        hostname: hdfs-namenode-01
        command: hadoop namenode
        environment:
            - DFS_NAMENODE_NAME_DIR=/var/local/hadoop/dfs/namenode
        ports:
            - "9870:9870"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "${KBD_DATA_DIR}/hdfs-namenode-01/logs:/var/log/hadoop"
            - "${KBD_DATA_DIR}/hdfs-namenode-01/dfs:/var/local/hadoop/dfs"
        networks:
            playground-net:

    hdfs-datanode-01:
        image: adruzenko/kbd-hadoop3:3.2.0
        hostname: hdfs-datanode-01
        command: hadoop datanode
        ports:
            - "9864:9864"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "${KBD_DATA_DIR}/hdfs-datanode-01/logs:/var/log/hadoop"
            - "${KBD_DATA_DIR}/hdfs-datanode-01/dfs:/var/local/hadoop/dfs"
        networks:
            playground-net:
        depends_on:
            - hdfs-namenode-01

    # Apache NiFi

    nifi-node-01:
        image: apache/nifi:1.9.2
        hostname: nifi-node-01
        ports:
            - "8080:8080"
            - "12100-12200:12100-12200"
        volumes:
            - "./etc/nifi:/opt/nifi/nifi-current/conf"
            - "./etc/hadoop:/etc/hadoop"
            - "./etc/nifi/nifi.truststore:/labs/nifi/bitstamp.truststore"
            - "${KBD_DATA_DIR}/nifi-node-01/flow:/var/lib/nifi/flow"
            - "${KBD_DATA_DIR}/nifi-node-01/flow_archive:/var/lib/nifi/flow_archive"
            - "${KBD_DATA_DIR}/nifi-node-01/templates:/var/lib/nifi/templates"
            - "${KBD_DATA_DIR}/nifi-node-01/logs:/opt/nifi/nifi-current/logs"
            - "${KBD_DATA_DIR}/nifi-node-01/database_repository:/opt/nifi/nifi-current/database_repository"
            - "${KBD_DATA_DIR}/nifi-node-01/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository"
            - "${KBD_DATA_DIR}/nifi-node-01/content_repository:/opt/nifi/nifi-current/content_repository"
            - "${KBD_DATA_DIR}/nifi-node-01/provenance_repository:/opt/nifi/nifi-current/provenance_repository"
        networks:
            playground-net:

    # Confluent Kafka

    kafka-node-01:
        image: confluentinc/cp-kafka:5.3.1
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zoo-node-01:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-node-01:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - 9092:9092
        volumes:
            - "${KBD_DATA_DIR}/kafka-node-01/data:/var/lib/kafka/data"
        depends_on:
            - zoo-node-01
        networks:
            playground-net:

    python-dev-01:
        image: python:3-stretch
        hostname: python-dev-01
        command: tail -f /dev/null
        volumes:
            - "./scripts:/scripts"
        depends_on:
            - kafka-node-01
        networks:
            playground-net:

networks:
  playground-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.101.0.0/24
