version: '3.5'
services:
    hdfs-namenode-01:
        image: adruzenko/kbd-hadoop3:latest
        hostname: hdfs-namenode-01
        command: hadoop namenode
        environment:
            - DFS_NAMENODE_NAME_DIR=/var/local/hadoop/dfs/namenode
        ports:
            - "9870:9870"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "./.kbd/hdfs-namenode-01/logs:/var/log/hadoop"
            - "./.kbd/hdfs-namenode-01/dfs/namenode:/var/local/hadoop/dfs/namenode"
            - "./.kbd/hdfs-namenode-01/dfs/journalnode:/var/local/hadoop/dfs/journalnode"
        networks:
            kbd-net:
                ipv4_address: 172.20.0.10

    hdfs-datanode-01:
        image: adruzenko/kbd-hadoop3:latest
        hostname: hdfs-datanode-01
        command: hadoop datanode
        ports:
            - "9864:9864"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "./.kbd/hdfs-datanode-01/logs:/var/log/hadoop"
            - "./.kbd/hdfs-datanode-01/dfs/datanode:/var/local/hadoop/dfs/datanode"
        networks:
            kbd-net:
                ipv4_address: 172.20.0.20
        depends_on:
            - hdfs-namenode-01

    yarn-resourcemanager-01:
        image: adruzenko/kbd-hadoop3:latest
        hostname: yarn-resourcemanager-01
        command: hadoop resourcemanager
        ports:
            - "8088:8088"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "./.kbd/yarn-resourcemanager-01/logs:/var/log/hadoop"
        networks:
            kbd-net:
                ipv4_address: 172.20.0.30

    yarn-nodemanager-01:
        image: adruzenko/kbd-hadoop3:latest
        hostname: yarn-nodemanager-01
        command: hadoop nodemanager
        ports:
            - "8042:8042"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "./.kbd/yarn-nodemanager-01/logs:/var/log/hadoop"
            - "./.kbd/yarn-nodemanager-01/tmp/mapred:/tmp/mapred"
        networks:
            kbd-net:
                ipv4_address: 172.20.0.40
        depends_on:
            - yarn-resourcemanager-01

    mapred-historyserver-01:
        image: adruzenko/kbd-hadoop3:latest
        hostname: mapred-historyserver-01
        command: hadoop historyserver
        ports:
            - "19888:19888"
        volumes:
            - "./etc/hadoop:/etc/hadoop"
            - "./.kbd/mapred-historyserver-01/logs:/var/log/hadoop"
            - "./.kbd/mapred-historyserver-01/tmp/mapred:/tmp/mapred"
        networks:
            kbd-net:
                ipv4_address: 172.20.0.50
        depends_on:
            - yarn-resourcemanager-01

networks:
  kbd-net:
    name: hadoop-min
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
